spring.application.name=paper0.1

spring.datasource.url=jdbc:mysql://localhost:3306/recommendation
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root

# 端口配置
server.port=8080

mybatis.mapper-locations=classpath*:com/tlias/paper0_1/**/*.xml
mybatis.type-aliases-package=com.tlias.paper0_1.entity
mybatis.configuration.map-underscore-to-camel-case=true